# Generated by Django 4.1.3 on 2022-12-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Adult', 'Adult student or parent'), ('Administrator', 'Administrator'), ('Director', 'Director')], max_length=13),
        ),
    ]
