# Generated by Django 4.1.3 on 2022-11-20 08:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(help_text='Please specify your available time for taking the lessons.', max_length=500)),
                ('lesson_numbers', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(240, message='Duration can not be bigger than 240')])),
                ('interval', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(8, message='Interval can not be bigger than 8')])),
                ('further_info', models.CharField(help_text='Please provide further information such as what you want to learn or your preferred teacher.', max_length=500)),
                ('approve_status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
