# Generated by Django 4.1.3 on 2022-11-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lesson_student_lesson_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='student',
        ),
    ]
