# Generated by Django 4.1.3 on 2022-12-02 21:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_rename_user_lesson_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('day_of_the_week', models.DateTimeField()),
                ('total_lesson_count', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(choices=[(30, '30'), (45, '45'), (60, '60')])),
                ('interval', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')])),
                ('teacher', models.CharField(max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('approve_status', models.BooleanField(default=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(choices=[(30, '30'), (45, '45'), (60, '60')], default=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='interval',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_paid', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('lesson_in_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lessons.approvedbooking')),
            ],
        ),
    ]
